name: Deploy Python Functions to Azure
on:
  push:
    branches: [ main ]  # Adjust if your main branch has a different name
  workflow_dispatch:    # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: cloud-computing-func  # Your function app name
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}